name: Test Workflow

on: [push]

jobs:
    run-unit-tests:
        name: Run Unit Tests
        runs-on: ubuntu-latest

        steps:
        
        - name: Check out repository
          uses: actions/checkout@v3

        - name: Use Node.js 18.x
          uses: actions/setup-node@v3

        - name: Install npm dependencies
          run: npm ci
        
        - name: Run unit tests
          run: npm run full-test-workflow # Run all tests and generate coverage and result data

        - uses: actions/upload-artifact@v3
          if: success() || failure()
          with:
            name: test-results
            path: test-results.json

        - name: Send coverage report to Coveralls
          uses: coverallsapp/github-action@v2
          if: success() || failure()
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
